apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    description: auth-srv
  generation: 2
  labels:
    k8s-app: auth-srv
    qcloud-app: auth-srv
  name: auth-srv
  namespace: test
spec:
  minReadySeconds: 10
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: auth-srv
      qcloud-app: auth-srv
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: auth-srv
        qcloud-app: auth-srv
    spec:
      containers:
      - env:
        - name: LANG
          value: C.UTF-8
        - name: TZ
          value: Asia/Shanghai
        - name: MCIRO_REGISTRY
          value: etcd
        - name: MICRO_REGISTRY_ADDRESS
          value: etcd:2379
        - name: MICRO_BROKER
          value: nats
        - name: MICRO_BROKER_ADDRESS
          value: nats:4222
        - name: MICRO_STORE_ADDRESS
          value: redis://:passthis1234@redis:6379
        image: ccr.ccs.tencentyun.com/mcbeam/auth_srv:latest
        imagePullPolicy: IfNotPresent
        name: auth-srv
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        workingDir: /src
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: qcloudregistrykey
      - name: tencenthubkey
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
